### ISSUE TITLE
Cannot read property 'Symbol(dartx.location)' of null

### ISSUE THREAD

**Issue by lhjandroid** [adrianflutur/webviewx#1]
hi
when i do js shell like this
```
document.getElementsByClassName("ad top")[0].style.display="none";
```
**error**
```
TypeError: Cannot read property 'style' of undefined
TypeError: Cannot read property 'Symbol(dartx.location)' of null
    at web$0._WebViewXWidgetState.new.[_updateSource] (http://localhost:54079/packages/webviewx/src/view/web.dart.lib.js:715:42)
    at http://localhost:54079/packages/webviewx/src/view/web.dart.lib.js:539:28
    at http://localhost:54079/dart_sdk.js:33443:33
    at internalCallback (http://localhost:54079/dart_sdk.js:25104:11)
```
but do on chrom it's ok.
**my code**
```
class WebPageState extends State<WebPage> {

  String js = '''
  document.getElementsByClassName("ad top")[0].style.display="none";
  ''';

  WebViewXController webviewController;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: WebViewX(
        initialContent: 'https://online-video-cutter.com/cn/',
        onWebViewCreated: (controller) {
          webviewController = controller;
          _evalRawJsInGlobalContext();
        },
        // jsContent: {
        //   EmbeddedJsContent(
        //     js: js
        //   )
        // },
      ),
    );
  }


  void _evalRawJsInGlobalContext() async {
    try {
      var result = await webviewController.evalRawJavascript(
        js,
        inGlobalContext: true,
      );
      print(result);
    } catch (e) {
      print(e);
    }
  }

}
```

**Comment by adrianflutur** [comment]
Hi, this happens because you are executing the JS inside the global window context (i.e. the main window, the browser), but your website is loaded inside the iframe window context.
You need to set `inGlobalContext: false`, or remove it entirely, like this

```dart
 void _evalRawJsInGlobalContext() async {
    try {
      var result = await webviewController.evalRawJavascript(js);
      print(result);
    } catch (e) {
      print(e);
    }
  }
```

**Comment by lhjandroid** [comment]
thanks for you replay.when change to
```
void _evalRawJsInGlobalContext() async {
    try {
      var result = await webviewController.evalRawJavascript(js);
      print(result);
    } catch (e) {
      print(e);
    }
  }
```
when run on chrom,i got a new error.
```
NoSuchMethodError: invalid member on null: 'callMethod'
TypeError: Cannot read property 'Symbol(dartx.location)' of null
    at web$0._WebViewXWidgetState.new.[_updateSource] (http://localhost:56989/packages/webviewx/src/view/web.dart.lib.js:715:42)
    at http://localhost:56989/packages/webviewx/src/view/web.dart.lib.js:539:28
    at http://localhost:56989/dart_sdk.js:33443:33
    at internalCallback (http://localhost:56989/dart_sdk.js:25104:11)
```
i found when run on chrome,i can't find the web Element. for this what way can i do?

**Comment by adrianflutur** [comment]
Alright, there are 3 problems here:

1.
Inside the source code, in `lib/src/view/web.dart`, around line 249 there is some commented code.
This code does exactly what you need. I experimented with it a little bit, and now I'm going to uncomment it.

2.
Your code here doesnt work because you're trying to make some changes to the webpage that is loaded inside the iframe, while having sourceType = `SourceType.URL`.

You cannot modify the content of the iframe if that iframe contains a webpage that is located on another domain. This is because an iframe is not like the mobile "webview" (which is somewhat like a mini-browser). This is a limitation of the iframe, not a package error.

If you need to modify something inside a webpage you need to set sourceType = `SourceType.URL_BYPASS`.
This sourceType will make the package actually "download" the entire website and set it as iframe's source. Then you can modify it as you wish.

3.
If you'll use `SourceType.URL_BYPASS`, as specified at 2. and you need to modify the webpage when the widget is initialized (initState or onWebViewCreated), you should wait for a while before doing so. This is because the package needs time to download the page.
So, you should use something like this: 
```dart
...
onWebViewCreated: (controller) {
        webviewController = controller;
        Future.delayed(Duration(milliseconds: 1500 /* or some other delay */), () {
          _evalRawJsInGlobalContext();
        });
      },
...
```

It's not perfect I know, but as it's said in the documentation: there are limitations because iframe != browser.

So, as a conclusion: If you need this to work: 
- use the latest package straight from github after I commit, or wait until the new version is published on pub.dev
- set the sourceType to `SourceType.URL_BYPASS`
- wait for a while before modifying something

I tested it, and it worked, but it seems that the CORS proxies didn't fetch everything on the page...and that's, again, a limitation.
![bypass_url_modify_source](https://user-images.githubusercontent.com/58974561/113914827-a7e4e400-97e6-11eb-8fc3-cc2ec1f24b71.gif)

**Comment by lhjandroid** [comment]
Thank you for your patience,i got it and looking forward to better it. ^_^

**Comment by adrianflutur** [comment]
Good, I'm closing this now. If you encounter any other problems, please open a new issue. Thanks
