### ISSUE TITLE
Html content not loading properly in mobile where as it is working fine in web?

### ISSUE THREAD

**Issue by CodingWithTashi** [adrianflutur/webviewx#19]
Hi @adrianflutur , Thanks again for great package, I am facing issue with loading html content in webview, it is working fine in web but in mobile it does not work propery even with latest version. 

Reproducible code: 
1. I have test,js,test.html in assets folder
a)In test.html
```
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src='assets/test.js'></script>
</head>
<body>

<h2>Test</h2>
<div class="container">
    <div class="content">
      
        <button class="button" onclick="backClick()">Back</button>
    </div>
</div>

</body>
</html>
```
b) In test.js
```
function backClick() {
alert("js called")
}
```   
And in flutter    
```
_loadHtmlFromAssets() {
    webviewController.loadContent(
      AppUtils.TEST_WEB_URL,
      SourceType.HTML,
      fromAssets: true,
    );
  }
```
though html content is loading in mobile js function is not triggering same goes for css style as well.
**Note: In web it is working fine js,html and css as well.**

**Comment by adrianflutur** [comment]
Hi,
This has nothing to do with this package. The fact that you cannot load separate .js or .css files from within an .html file located in the assets on mobile, is an old missing feature from the webview_flutter, which I tried to compensate for by creating that `loadContent` function from the controller.

It works on web because the web is different from the mobile version. The web version places the assets on the `http://localhost:port/assets/HERE` path (if I remember correctly), and thats why it works - because it basically hosts those assets like they would be hosted on some CDN. That means it can find the assets there (your `<script src='assets/test.js'></script>`, specifically).
On mobile the hosting-thing is not happening (obviously, since it's mobile not web), so your .html file can't find and load other .js or .css resources.

Now, there are 3 ways to work around this:
1. If you own the .js or .css or whatever resource you want to add, you can just place(hardcode) it inside the .html file instead of getting it from outside (i.e. have a single .html file inside your /assets). 
2. If you do not own the .js or .css (like jQuery, for example), just add the link from a CDN and it will download it automatically.
3. (Only for Javascript content) You can also use the `jsContent` property from the WebViewX widget to embed Javascript code inside the page at runtime. It will have the same effect as number 1, but you may have extra control over what gets inside the page (also platform-dependent stuff, etc).

**Comment by CodingWithTashi** [comment]
Unfortunately my css and js content are too huge to fit in single file and on top of that it is not only single js or css, I have more file than is linked to root html. 
It would be great help if there is any work around to this since I dont want to use some other webview. But If there is no other way than I will end up using different plugin for mobile which I don't want to.

**Comment by adrianflutur** [comment]
@CodingWithTashi 
There would be another two work arounds for this:

      4. Host theese additional files on some server, then you can point to them via https://...and they will load
      5. Compute a custom html page by manually embedding all your necessary assets inside a single String, then load it using the controller

There is this function inside `html_utils.dart`:
```
static String embedInHtmlSource({
    required String source,
    required String whatToEmbed,
    required EmbedPosition position,  
})
```
You can combine this function with loading your assets from the /assets/ folder by using rootBundle:
```
final content = await rootBundle.loadString('assets/some_asset.js');
```
, and you get this:
```
final source = await rootBundle.loadString('assets/some_page.html');
final someJsLibraryFromAssets = await rootBundle.loadString('assets/some_library.js');

final embeddedContent = HtmlUtils.embedInHtmlSource(
   source: source, 
   whatToEmbed: someJsLibraryFromAssets,
   position: EmbedPosition.ABOVE_HEAD_CLOSE_TAG, // or other position
);
webViewXController.loadContent(
      embeddedContent,
      SourceType.HTML,
);
```

If none of theese 5 methods suit your use-case then I'm not sure there is anything else I can do..
