### ISSUE TITLE
Can i open iframe with a particular id in flutter web?

### ISSUE THREAD

**Issue by shivam-cashify** [adrianflutur/webviewx#23]

**Comment by shivam-cashify** [comment]
Actually i want to use html renderer but when i am doing so, i am not able to get iframe element from the document object in javascript using below code :
`var iframe = document.getElementsByTagName('iframe');`

but it works fine in canvasKit renderer.
Please tell if it is possible to get iframe or to start iframe with my own defined ID.

**Comment by adrianflutur** [comment]
Hi, as far as I know, on the `html` renderer the `iframe` is somehow hidden inside the document's `shadowRoot`.
It has nothing to do with IDs (as long as you query by tag name and not by id).

**Comment by adrianflutur** [comment]
After evaluating this, I could implement it but I'm not sure this is a good idea because the iframes are being created with a random ID for a specific reason, and that is because otherwise the user might forget to pass an ID, or might pass the same ID twice, and the iframe(s) will start to behave weird.
So the best advice is to use the methods from the webviewXController to do/call whatever you need, but keep the IDs random.
Closing this for now, please open a new issue if you need more help.
